In [6]:
# !git clone https://github.com/eriklindernoren/PyTorch-YOLOv3
# %cd PyTorch-YOLOv3/
# !pip3 install poetry --user
# !poetry install
# !./weights/download_weights.sh
# !pip3 install pytorchyolo --user
# !poetry run yolo-test --weights weights/yolov3.weights

!pip uninstall -y torch torchvision
!pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116

^C
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.7/site-packages/pip/_inte

In [ ]:
from pytorchyolo.models import load_model_own


In [1]:
%cd /app/src

import cv2
import torch
import os
import numpy as np
import matplotlib.pyplot as plt

from pytorchyolo import detect, models

from utils.viz_utils import draw_bounding_boxes


import sys

def include_utils():
    parent_directory = os.path.abspath('/app/utils')
    sys.path.append(parent_directory)

include_utils()


# Load the YOLO model
model = models.load_model(
  "/app/PyTorch-YOLOv3/config/yolov3.cfg",
  "/app/bin/model_files/yolov3.weights")


/app/src


In [ ]:

# Load the image as a numpy array
img = cv2.imread("/app/data/images/embedding_tester/apple_2.jpg")

with open("/app/PyTorch-YOLOv3/data/coco.names", 'r') as rf:
    classes = rf.read().split('\n')

# Convert OpenCV bgr to rgb
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

device = torch.device('cuda')

model.to(device)

# Runs the YOLO model on the image
boxes = detect.detect_image(model, img)

draw_bounding_boxes(img, boxes, classes)

# for box in boxes:
#   img = cv2.rectangle(img, box[:2].astype(int), box[2:4].astype(int), (0,0,0), 10)

plt.imshow(img)

<hr>
<hr>

# storage

<hr>
<hr>

<hr>
<hr>
<h1>EXPERIMENTS WITH MODIFIED SOURCE HERE ON</h1>

In [ ]:
%cd /app/src

import cv2
import torch
import os
import numpy as np
import matplotlib.pyplot as plt

from pytorchyolo import detect, models

from utils.viz_utils import draw_bounding_boxes

import sys

with open("/app/PyTorch-YOLOv3/data/coco.names", 'r') as rf:
    classes = rf.read().split('\n')
    
def include_modules(libdir):
    parent_directory = os.path.abspath(libdir)
    sys.path.append(parent_directory)

include_modules('/app/src/utils')

device = torch.device('cuda')

# Load the YOLO model
model = models.load_model_own(
  "/app/PyTorch-YOLOv3/config/yolov3.cfg",
  "/app/bin/model_files/yolov3.weights").to(device)


# model

In [ ]:

from pytorchyolo.models import load_model
from pytorchyolo.utils.utils import load_classes, rescale_boxes, non_max_suppression, print_environment_info
from pytorchyolo.utils.datasets import ImageFolder
from pytorchyolo.utils.transforms import Resize, DEFAULT_TRANSFORMS
from pprint import pprint

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.ticker import NullLocator
import torchvision.transforms as transforms

img_size=416
conf_thres=0.5
nms_thres=0.5

model.eval()  # Set model to evaluation mode


img = cv2.imread("/app/data/images/embedding_tester/apple_2.jpg")


# Convert OpenCV bgr to rgb
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


# Configure input
input_img = transforms.Compose([
    DEFAULT_TRANSFORMS,
    Resize(img_size)])(
        (img, np.zeros((1, 5))))[0].unsqueeze(0)

if torch.cuda.is_available():
    input_img = input_img.to("cuda")

# Get detections
with torch.no_grad():
    detections = model(input_img)
    # detections = non_max_suppression(detections, conf_thres, nms_thres)
    # detections = rescale_boxes(detections[0], img_size, img.shape[:2])


In [2]:
from utils.yolo_utils import yolo_model
from utils.viz_utils import draw_bounding_boxes


test_yolo = yolo_model()

In [5]:
import os

img_size=416
conf_thres=0.5
nms_thres=0.01

image_paths = [os.path.join("/app/data/images/embedding_tester/", im_name) for im_name in os.listdir("/app/data/images/embedding_tester/")]
# img = cv2.imread("/app/data/images/embedding_tester/apple_3.jpg")

embedding_list = []
# for impath in image_paths:
# impath = image_paths[4] 
# img = cv2.imread(impath)
embedding_details, embeddings_matrix = test_yolo.get_embeddings(image_paths[:20],
            img_size=img_size,
            conf_thres=conf_thres,
            nms_thres=nms_thres,
            head = 0,
            embedding_window_size = 3,
            viz = False)
# print(embeddings[0].shape)
# embedding_list+=embeddings

boxes : [[116.08516 150.97758 387.11856 238.94258]
 [390.05267 239.07567 538.6677  378.15506]]
 object embedding_locations : [[ 4  4  7  7]
 [ 8  8 11 11]]
boxes : [[143.6355  272.41232 270.64465 397.59027]]
 object embedding_locations : [[ 8  3 11  6]]
boxes : [[ 64.03949 302.52893 201.40988 425.     ]]
 object embedding_locations : [[10  1 13  4]]
boxes : [[133.48222 134.94226 274.91492 260.61563]]
 object embedding_locations : [[5 4 8 7]]
boxes : [[451.09494 274.66785 593.2746  426.70435]
 [113.97594 279.29468 245.0633  414.5993 ]]
 object embedding_locations : [[ 9  9 12 12]
 [ 9  2 12  5]]
boxes : [[385.3665  286.03903 524.2553  427.64282]
 [155.627   236.00618 352.54803 352.12186]]
 object embedding_locations : [[ 8  8 11 11]
 [ 6  4  9  7]]
boxes : [[  8.050338 282.29752  207.19604  427.      ]]
 object embedding_locations : [[ 9  1 12  4]]
boxes : [[274.91138 197.28207 633.5343  457.9926 ]]
 object embedding_locations : [[ 7  8 10 11]]
boxes : [[ 62.113834   0.       579.10724 

In [ ]:
embedding_details['source_paths']

In [ ]:
testim = cv2.imread(image_paths[0])

In [ ]:
# a = []
a += ["impat" for i in range(10)]
a

In [ ]:
"""
pad embeddings which dont have 5x5
"""


a = embedding_list[0]
for i in range(1,len(embedding_list)):
    print(f" a shape : {a.shape} , embedding_listp[i] shape : {embedding_list[i].shape}")
    a = np.concatenate([a, embedding_list[i]])

print(a.shape)

In [ ]:
type(detections[0])
print(f"num layer outputs : {len(detections[0])}\n")
print(f"num heads = {len(detections[1])}\n")
for ind, i in enumerate(model.module_defs) :
    if i['type'] == 'yolo':
        print(f"\nlayer {ind} : name : {i['type']}\n") 
        print(" details : \n")
        pprint(i)
        print("\n")
    else:
        print(f"layer {ind} : name : {i['type']}") 

In [ ]:
# def get_layer_details(model, detections, layer_num):
#     print("layer details : \n")
#     pprint(model.module_defs[layer_num])
#     print(f"\noutput shape : {detections[0][layer_num].shape}")


# img_size=416
# conf_thres=0.5
# nms_thres=0.5

# for ind, head_ind in enumerate([82, 94, 106]):
#     img = cv2.imread("/app/data/images/embedding_tester/apple_2.jpg")   
#     get_layer_details(model, detections, head_ind)
#     head_detections = detections[0][head_ind]
#     print(f"head {ind + 1} : total boxes detected  : {head_detections.shape}")
#     head_detections = non_max_suppression(head_detections, conf_thres, nms_thres)
#     print(f"num boxes post supression : {head_detections[0].shape}")
#     head_detections = rescale_boxes(head_detections[0], img_size, img.shape[:2])
#     boxes = head_detections.numpy()
#     image = draw_bounding_boxes(img, boxes, classes)
#     plt.imshow(image[:, :, ::-1])
#     plt.show()

### the 83nd , 95th and 107th layers are heads <br>

### we will analyse the emebddings corresponding to each of the layers 1 by 1.<br>

### starting with the 1st head : 83rd layer

#### the heads are actually just reshaping layer, that apply the final scaling scaling transforms to convert logits to xyxy conf cls
#### the layers before heads are fully connected linear layers, so these are the ones that actually do the classification and regresssions
#### Therefore, to extract the embeddings we take the the 2nd predecessor of a head, so here, we take 81st layer.


In [ ]:

def get_layer_details(model, detections, layer_ind):
    print(f"embeddings of layer : {layer_ind}:\n")
    pprint(model.module_defs[layer_ind])
    print(f"\noutputs shape : {detections[0][layer_ind].shape}")

    

get_layer_details(model, detections, 80)

raw_embeddings = detections[0][80]
outputs = model.module_list[81](raw_embeddings)

raw_embeddings.max()

In [ ]:
for i in model.module_defs:
    print(i["type"])

In [ ]:
def raw_predict(img, input_img_size, raw_outputs, conf_thres, nms_thres, viz = False, reverse_img_for_viz = True):
    head_detections = non_max_suppression(raw_outputs, conf_thres, nms_thres)
    # print(f"num boxes post supression : {head_detections[0].shape}")
    head_detections = rescale_boxes(head_detections[0], input_img_size, img.shape[:2])
    boxes = head_detections.numpy()
    image = draw_bounding_boxes(img, boxes, classes)
    if reverse_img_for_viz:
        image = image[:, :, ::-1]
    if viz:
        plt.imshow()
        plt.show()
    return image, boxes    

def predict_from_embedding(raw_embeddings,
                           model,
                           embeddding_layer_ind,
                           input_img_size,
                           conf_thres,
                           nms_thres,
                           viz = False,
                           reverse_img_for_viz = True):
    outputs = model.module_list[embeddding_layer_ind + 1](raw_embeddings)
    outputs = model.module_list[embeddding_layer_ind + 2][0](outputs, img_size)
    image = raw_predict(img, input_img_size, outputs, conf_thres, nms_thres, viz, reverse_img_for_viz)
    return image


# EMBEDDING OCCULSION VISUALIZATION VIDEO GENERATION

In [ ]:
# from utils.viz_utils import create_frame

# #XXXXXXXXXXXXXXXXXXXXXXXXXX     video details
# # frames,
# # output_path = '/app/bin/outputs/embedding_occulsion_analysis_head_1.mp4'
# output_path = '/app/bin/outputs/temp.mp4'
# fps=5
# frame_size=(800, 400)

# frame_counter = 0

# fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Using 'mp4v' for compatibility
# video = cv2.VideoWriter(output_path, fourcc, fps, frame_size)
# #XXXXXXXXXXXXXXXXXXXXXXXXXXX



# embedding_ind = 80 # head 1


# num_rows, num_cols = raw_embeddings.shape[-2:]
# for window_size in range(1,int(round(2*num_rows/3))):
#     for i in range(num_rows-window_size):
#         for j in range(num_cols-window_size):

#             img = cv2.imread("/app/data/images/embedding_tester/apple_2.jpg")   

#             img_size = input_img.size(2)
#             raw_embeddings = detections[0][embedding_ind].clone()

#             raw_embeddings[:,:,i:i+window_size,j:j+window_size] = 0

#             viz_image = predict_from_embedding(raw_embeddings,
#                                     model,
#                                     embedding_ind,
#                                     img_size,
#                                     conf_thres,
#                                     nms_thres)
            
#             raw_embeddings[0, 0, :, :].detach().cpu().numpy()

            
#             frame = create_frame([raw_embeddings[0, 0, :, :].detach().cpu().numpy(), viz_image], ["embedding", "results"], figsize=(10, 5))
            
#             resized_frame = cv2.resize(frame, frame_size)  
#             video.write(resized_frame)

#             frame_counter+=1
#             if frame_counter % 30 == 0:
#                 print(f"{frame_counter} frames over")
                
# video.release()



In [ ]:
"""
getting pred cell memberships
"""
embeddding_layer_ind = 80
input_img_size = img_size
raw_embeddings = detections[0][embeddding_layer_ind]

outputs = model.module_list[embeddding_layer_ind + 1](raw_embeddings)
outputs = model.module_list[embeddding_layer_ind + 2][0](outputs, img_size)
head_detections = non_max_suppression(outputs, conf_thres, nms_thres)
head_detections = rescale_boxes(head_detections[0], input_img_size, img.shape[:2])
boxes = head_detections.numpy()

vizimg = img.copy()

vizimg = draw_bounding_boxes(vizimg, boxes, classes)
plt.imshow(vizimg)
plt.show()

In [ ]:
vizimg = img.copy()
batch_size, num_channels , grid_num_rows, grid_num_cols = detections[0][embeddding_layer_ind].shape 

grid_dim_row = int(round(img.shape[0] / grid_num_rows))
grid_dim_col = int(round(img.shape[1] / grid_num_cols))
grid_dims = np.array([grid_dim_col, grid_dim_row])
print(grid_dims)
centers = (boxes[:, 2:4] - boxes[: , :2])/2 + boxes[: , :2]
mem_starts_xy = centers // grid_dims # we need xlength , ylength, not row_length, col_length
mem_cells_mins = mem_starts_xy * grid_dims
print(mem_cells_mins)
mem_cells_maxs = mem_cells_mins + grid_dims
print(mem_cells_maxs)
# mem_cell_boxes = np.concatenate([centers, mem_cells_maxs], axis = 1).astype(int)
mem_cell_boxes = np.concatenate([mem_cells_mins, mem_cells_maxs], axis = 1).astype(int)

for center in centers.astype(int):
    vizimg = cv2.circle(vizimg, (center[0], center[1]), 10, (0,0,0), 17)
    vizimg = cv2.circle(vizimg, (center[0], center[1]), 10, (255,255,255), 3)

for xmin, ymin ,xmax, ymax in mem_cell_boxes.astype(int):
    vizimg = cv2.rectangle(vizimg, (xmin, ymin), (xmax, ymax), (0,0,255), 17)


plt.imshow(vizimg)
plt.show()      



In [ ]:
centers

In [ ]:
mem_starts_xy

In [ ]:
a = np.zeros_like(img)
a[394:422, 560:588] = 250
plt.imshow(a)
plt.show()

a = np.zeros([13,13])
r,c = mem_starts_xy[0][::-1].astype(int)
a[r,c] = 100
plt.imshow(a)
plt.show()

In [ ]:
detections.shape

In [ ]:
print(centers[:, ::-1] // grid_dims[::-1])
print(mem_starts_xy[:, ::-1])

In [ ]:
from utils.viz_utils import create_frame

viz = True

embeddding_layer_ind = 80

outputs_layer = 82

conf_thres=0.5 
nms_thres=0.5
input_img_size = 416

raw_outputs = detections[0][outputs_layer]


image, boxes = raw_predict(img, input_img_size, raw_outputs, conf_thres, nms_thres, viz = False, reverse_img_for_viz = True)

batch_size, num_channels , grid_num_rows, grid_num_cols = detections[0][embeddding_layer_ind].shape 

grid_dim_row = int(round(img.shape[0] / grid_num_rows))
grid_dim_col = int(round(img.shape[1] / grid_num_cols))
grid_dims = np.array([grid_dim_col, grid_dim_row])

centers = (boxes[:, 2:4] - boxes[: , :2])/2 + boxes[: , :2]

# from xy to row col
mem_starts_rowcol = centers[:, ::-1] // grid_dims[::-1]

embedding_slice_min = np.maximum(mem_starts_rowcol - 2, np.zeros_like(mem_starts_rowcol)).astype(int)
embedding_slice_max = np.minimum(mem_starts_rowcol + 3, np.ones_like(mem_starts_rowcol) * (grid_dims[::-1] )).astype(int)


#####
viz_embedding = np.concatenate([embedding_slice_min, embedding_slice_max], axis = 1)

print(viz_embedding)
print(mem_starts_rowcol)

raw_embedding = detections[0][80].detach().cpu().numpy()

# #XXXXXXXXXXXXXXXXXXXXXXXXXX     video details
# frames,
# output_path = '/app/bin/outputs/embedding_occulsion_analysis_head_1.mp4'
output_path = '/app/bin/outputs/embedding_assignment_method.mp4'
fps=0.4
frame_size=(800, 400)

frame_counter = 0

fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Using 'mp4v' for compatibility
video = cv2.VideoWriter(output_path, fourcc, fps, frame_size)
# #XXXXXXXXXXXXXXXXXXXXXXXXXXX


embeddings = []
for ind, (rowmin, colmin, rowmax, colmax) in enumerate(viz_embedding.astype(int)):
    embeddings.append(raw_embedding[:, :, rowmin:rowmax, colmin:colmax])

    if viz == True:
        
        vizimg = img.copy()
        vizimg = cv2.rectangle(vizimg, (colmin * grid_dim_row, rowmin * grid_dim_col) , (colmax * grid_dim_row , rowmax * grid_dim_col), (0,0,0) , 15)
        vizimg = draw_bounding_boxes(vizimg, boxes[ind][None, ...], classes)
        center_x , center_y = centers[ind].astype(int)
        vizimg = cv2.circle(vizimg, (center_x, center_y), 20, (0,0,0), 22)
        vizimg = cv2.circle(vizimg, (center_x, center_y), 20, (255,255,255), 5)

        viz_emb = raw_embedding[0, 0, :, :].copy()
        r, c = mem_starts_rowcol[ind].astype(int)
        viz_emb[rowmin:rowmax, colmin:colmax] = 0.0
        viz_emb[r,c] = 0.75

            
        frame = create_frame([viz_emb, vizimg], ["embedding", "results"], figsize=(10, 5))
        
        resized_frame = cv2.resize(frame, frame_size)  
        video.write(resized_frame)

        plt.imshow(frame[:, :, ::-1])
        plt.show()

video.release()

In [ ]:
detections[0][0][0][0][0][0]

In [ ]:
a = detections
a[0][0][0][0][0][0] = 196996.3242

In [ ]:

mem_starts_rowcol = centers[:, ::-1] // grid_dims[::-1]
embedding_slice_min = np.maximum(mem_starts_rowcol - 2, np.zeros_like(mem_starts_rowcol)).astype(int)
embedding_slice_max = np.minimum(mem_starts_rowcol + 3, np.ones_like(mem_starts_rowcol) * (grid_dims[::-1] )).astype(int)

viz_embedding = np.concatenate([embedding_slice_min, embedding_slice_max], axis = 1)



In [ ]:


a = np.zeros([13,13])
(rowmin, colmin), (rowmax, colmax) = embedding_slice_min[0] , embedding_slice_max[0]
r, c = mem_starts_rowcol[0].astype(int)
a[rowmin:rowmax, colmin:colmax] = 50
a[0:4,10] = 100
a[10, 0] = 100
plt.imshow(a)
plt.show()

In [ ]:
a

In [ ]:
# import cv2
# import numpy as np
# import matplotlib.pyplot as plt
# from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

# import cv2
# import numpy as np
# import matplotlib.pyplot as plt
# from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


# def create_frame(images, titles, figsize=(10, 5)):
#     layout = (1, len(images))  # Change layout to have enough spots for each image
    
#     total_subplots = layout[0] * layout[1]

#     fig, axs = plt.subplots(layout[0], layout[1], figsize=figsize)
#     axs = axs.flatten() if layout[0] * layout[1] > 1 else [axs]
    
#     # Hide any unused subplots
#     for ax in axs[len(images):]:
#         ax.axis('off')
    
#     for ax, img, title in zip(axs[:len(images)], images, titles):
#         ax.imshow(img, aspect='auto')
#         ax.set_title(title)
#         ax.axis('off')
    
#     # plt.subplots_adjust(wspace=0.1, hspace=0.2)  # Adjust spacing to prevent overlap
    
#     canvas = FigureCanvas(fig)
#     canvas.draw()
#     frame = np.array(canvas.renderer.buffer_rgba())
#     plt.close(fig)
    
#     frame = cv2.cvtColor(frame, cv2.COLOR_RGBA2BGR)
#     return frame



# def create_video(frames, output_path='output_video.mp4', fps=10, frame_size=(1920, 1080)):
#     fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Using 'mp4v' for compatibility
#     video = cv2.VideoWriter(output_path, fourcc, fps, frame_size)

#     for frame in frames:
#         resized_frame = cv2.resize(frame, frame_size)  # Resize to ensure compatibility
#         video.write(resized_frame)
    
#     video.release()

# # Example usage
# images = [np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8) for _ in range(20)]
# titles = ['Image 1', 'Image 2', 'Image 3', 'Image 4']

# frames = [create_frame([img, img],titles,  figsize=(8, 8)) for img in images]

# create_video(frames, 'output_video.mp4', fps=5, frame_size=(800, 400))


