## Setup


In [ ]:
# # !git clone https://github.com/eriklindernoren/PyTorch-YOLOv3
# # %cd PyTorch-YOLOv3/
# # !pip3 install poetry --user
# # !poetry install
# # !./weights/download_weights.sh
# # !pip3 install pytorchyolo --user
# # !poetry run yolo-test --weights weights/yolov3.weights

# !pip uninstall -y torch torchvision
# !pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116

## Loading the yoloV3 model

In [1]:
from utils.yolo_utils import yolo_model
from utils.viz_utils import draw_bounding_boxes


test_yolo = yolo_model()

## Loading images, Doing inference, Isolating object-specific embedding Slices, saving resulting embedddings and relevant details as pickle files

In [3]:
import os

img_size=416
conf_thres=0.5
nms_thres=0.01

image_paths = [os.path.join("/app/data/images/embedding_tester/", im_name) for im_name in os.listdir("/app/data/images/embedding_tester/")]
# img = cv2.imread("/app/data/images/embedding_tester/apple_3.jpg")

embedding_list = []
embedding_details, embeddings_matrix = test_yolo.get_embeddings(image_paths[:20],
            img_size=img_size,
            conf_thres=conf_thres,
            nms_thres=nms_thres,
            head = 0,
            embedding_window_size = 3,
            viz = False)

 object embedding_locations : [[5 5 8 8]]
 object embedding_locations : [[5 5 8 8]]
 object embedding_locations : [[5 5 8 8]]
 object embedding_locations : [[2 2 5 5]]
 object embedding_locations : [[ 2  3  5  6]
 [ 8  4 11  7]
 [ 4  3  7  6]
 [ 5  6  8  9]]
 object embedding_locations : [[ 6  4  9  7]
 [ 5  9  8 12]]
 object embedding_locations : [[6 3 9 6]]
 object embedding_locations : [[5 5 8 8]]
 object embedding_locations : [[6 6 9 9]]
releasing video

saved file name : 3c94b82dfec85ea088126f4d76111bc6_yolo_numims_9_embwin_3

